"""Add uuid column to lessons

Revision ID: e4a6e42aa955
Revises: 7f878c59029a
Create Date: 2023-04-11 04:16:53.298894+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4a6e42aa955'
down_revision = '7f878c59029a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('id', sa.UUID(), nullable=False))
    op.alter_column(
        'lessons', 'name', existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        'lessons', 'week_day_number', existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        'lessons',
        'week_parity',
        existing_type=postgresql.ENUM('even', 'odd', name='week_parities'),
        nullable=True
    )
    op.alter_column(
        'lessons',
        'teacher_full_name',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    op.alter_column(
        'lessons',
        'lesson_type',
        existing_type=postgresql.ENUM(
            'lecture', 'practical', 'laboratory', name='lesson_types'
        ),
        nullable=True
    )
    op.alter_column(
        'lessons', 'auditorium', existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'lessons', 'auditorium', existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        'lessons',
        'lesson_type',
        existing_type=postgresql.ENUM(
            'lecture', 'practical', 'laboratory', name='lesson_types'
        ),
        nullable=False
    )
    op.alter_column(
        'lessons',
        'teacher_full_name',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.alter_column(
        'lessons',
        'week_parity',
        existing_type=postgresql.ENUM('even', 'odd', name='week_parities'),
        nullable=False
    )
    op.alter_column(
        'lessons',
        'week_day_number',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'lessons', 'name', existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column('lessons', 'id')
    # ### end Alembic commands ###
