"""Alter columns start time and end time to time field in lesson sequences table

Revision ID: 2391158ab38c
Revises: 6e6ef1215ead
Create Date: 2023-04-11 03:48:26.257715+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2391158ab38c'
down_revision = '6e6ef1215ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'lesson_sequences',
        'start_time',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Time(),
        existing_nullable=False
    )
    op.alter_column(
        'lesson_sequences',
        'end_time',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Time(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'lesson_sequences',
        'end_time',
        existing_type=sa.Time(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False
    )
    op.alter_column(
        'lesson_sequences',
        'start_time',
        existing_type=sa.Time(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False
    )
    # ### end Alembic commands ###
