"""Drop constraint sequence number on lessons table

Revision ID: 7f878c59029a
Revises: 2391158ab38c
Create Date: 2023-04-11 04:05:36.069664+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '7f878c59029a'
down_revision = '2391158ab38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_lessons_sequence_number_lesson_sequences',
        'lessons',
        type_='foreignkey'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        'fk_lessons_sequence_number_lesson_sequences',
        'lessons',
        'lesson_sequences', ['sequence_number'], ['number'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###
