"""Create table `lessons`

Revision ID: 6e6ef1215ead
Revises: 28473bcc303b
Create Date: 2023-04-04 04:10:54.447182+00:00

"""
import sqlalchemy as sa
from alembic import op

from smart_schedule_nsau.adapters.database.tables import (
    LESSON_TYPES_ENUM,
    WEEK_PARITIES_ENUM,
)

# revision identifiers, used by Alembic.
revision = '6e6ef1215ead'
down_revision = '28473bcc303b'
branch_labels = None
depends_on = None


def upgrade():
    WEEK_PARITIES_ENUM.create(op.get_bind(), checkfirst=True)
    LESSON_TYPES_ENUM.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'lessons', sa.Column('name', sa.String(), nullable=False),
        sa.Column('week_day_number', sa.Integer(), nullable=False),
        sa.Column('sequence_number', sa.Integer(), nullable=False),
        sa.Column('week_parity', WEEK_PARITIES_ENUM, nullable=False),
        sa.Column('teacher_full_name', sa.String(), nullable=False),
        sa.Column('lesson_type', LESSON_TYPES_ENUM, nullable=False),
        sa.Column('auditorium', sa.String(), nullable=False),
        sa.Column('study_group_name', sa.String(), nullable=False),
        sa.Column('subgroup', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['sequence_number'], ['lesson_sequences.number'],
            name=op.f('fk_lessons_sequence_number_lesson_sequences'),
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['study_group_name'], ['study_groups.name'],
            name=op.f('fk_lessons_study_group_name_study_groups'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint(
            'name',
            'week_day_number',
            'week_parity',
            'teacher_full_name',
            'lesson_type',
            'auditorium',
            name=op.f('pk_lessons')
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    # ### end Alembic commands ###

    WEEK_PARITIES_ENUM.drop(op.get_bind(), checkfirst=True)
    LESSON_TYPES_ENUM.drop(op.get_bind(), checkfirst=True)
