"""Create table `lesson_sequences`

Revision ID: c54ad3306e80
Revises: 62a4de750b52
Create Date: 2023-04-03 04:01:07.721172+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c54ad3306e80'
down_revision = '62a4de750b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'lesson_sequences', sa.Column('number', sa.Integer(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('number', name=op.f('pk_lesson_sequences'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_sequences')
    # ### end Alembic commands ###
